container:
  image: gcc:latest

make_task:
  fix_script: echo '[ apt-get = "$1" ] || exec "$@"; shift; exec apt-get -y "$@"' > /bin/sudo; chmod +x /bin/sudo
  prep_script: git submodule update --init --recursive
  check_script: a="`git status --porcelain`" && [ -z "$a" ]
  debian_script: apt-get update; make debian
  make_script: make

