container:
  image: gcc:latest

make_task:
  prep_script: git submodule update --init --recursive
  check_script: a="`git status --porcelain`" && [ -z "$a" ]
  debian_script: make debian
  make_script: make

